name: Generate Snake

on:
schedule:
- cron: "0 */6 * * *"
workflow_dispatch:

permissions:
contents: write

jobs:
generate:
runs-on: ubuntu-latest

```
steps:
  - name: Generate Snake
    uses: Platane/snk@v3
    with:
      github_user_name: Illakiya-B
      outputs: |
        dist/github-snake.svg
        dist/github-snake-dark.svg?palette=github-dark

  - name: Deploy
    uses: peaceiris/actions-gh-pages@v3
    with:
      publish_dir: dist
      publish_branch: output
      github_token: ${{ secrets.GITHUB_TOKEN }}
```

